DEFAULT_PROFESSION = "abogados"
DEFAULT_CITY = "Elche"
HEADLESS = False

# Rate limiting & scroll params
DELAY_INITIAL_LOAD = 3.0
DELAY_AFTER_CONSENT = 3.0
DELAY_PER_CARD_CLICK = 4.0
DELAY_SCROLL_AFTER_EXTRACT = 2.0
JITTER_RANGE = 0.2
RETRY_BACKOFF_BASE = 2
MAX_EXTRACTION_RETRIES = 3
